// export const houseData = [
//   {
//     id:"meta-123",
//     name: "Minimalist Villa",
//     description: "Clean lines and open spaces define this modern minimalist design",
//     type: "minimal",
//     color: "#ffffff",
//     features: ["pool", "patio"],
//     thumbnail: "/placeholder.svg?height=200&width=300",
//     dimensions: { width: 30, depth: 40 },
//   },
//   {
//     id:"meta-456",
//     name: "Beachfront Retreat",
//     description: "Panoramic ocean views with indoor-outdoor living spaces",
//     type: "beach",
//     color: "#f5f5f0",
//     features: ["pool", "patio"],
//     thumbnail: "/placeholder.svg?height=200&width=300",
//     dimensions: { width: 35, depth: 45 },
//   },
//   {
//     id:"meta-789",
//     name: "Mountain Villa",
//     description: "Luxury alpine design with natural materials and cozy spaces",
//     type: "mountain",
//     color: "#e0e0d0",
//     features: ["pool", "patio"],
//     thumbnail: "/placeholder.svg?height=200&width=300",
//     dimensions: { width: 40, depth: 50 },
//   },
//   {
//     id:"meta-101112",
//     name: "Desert Oasis",
//     description: "Sustainable design that embraces the desert landscape",
//     type: "desert",
//     color: "#e8e0d5",
//     features: ["pool", "patio"],
//     thumbnail: "/placeholder.svg?height=200&width=300",
//     dimensions: { width: 45, depth: 55 },
//   },
//   {
//     id:"meta-131415",
//     name: "Tropical Paradise",
//     description: "Open-air living with lush surroundings and natural ventilation",
//     type: "tropical",
//     color: "#f0f5f0",
//     features: ["pool", "patio"],
//     thumbnail: "/placeholder.svg?height=200&width=300",
//     dimensions: { width: 50, depth: 60 },
//   },
//   {
//     id:"meta-161718",
//     name: "Urban Penthouse",
//     description: "Sophisticated city living with floor-to-ceiling windows and rooftop amenities",
//     type: "urban",
//     color: "#f0f0f0",
//     features: ["pool", "patio"],
//     thumbnail: "/placeholder.svg?height=200&width=300",
//     dimensions: { width: 35, depth: 35 },
//   },
// ]
